name: Running Code Coverage

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "seeders/**"
  push:
    branches: [ dev ]
    paths:
      - "src/**"
      - "seeders/**"
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./
      run: |
        npm install
    - name: Run the tests
      run: |
        npm test -- --coverage
